version: "3.9"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_USER: appuser
      POSTGRES_DB: appdb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  api:
    build: ./api
    environment:
      - NODE_ENV=development
    env_file:
      - ./api/.env
    depends_on:
      - db
      - pyservice
    ports:
      - "3001:3001"

  pyservice:
    build: ./python_service
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "5173:5173"
